Hw17 MaksimKez
dkobzin/tms-net15-onl pull request #78
Opened 2024-04-04 06:42 UTC by MaksimKez

Задание сделано, но есть недочет. После завершения работы новые (измененные) настройки не отображаются в appsettings.Development.json (как и в appsettings.json). Как это решить не знаю :(

2024-04-04 07:18 UTC, dkobzin commented
Добрый день! Убедительная просьба - не мержить самостоятельно PR в main.

2024-04-04 07:27 UTC, dkobzin requested changes

2024-04-04 07:27 UTC, dkobzin commented on MaksimKez/HW17/hw16/hw16/Models/MeetingSettings.cs
> +    [Serializable]
аттрибуты тут не нужны

2024-04-04 07:27 UTC, dkobzin commented on MaksimKez/HW17/hw16/hw16/Models/MeetingSettings.cs
> +        [JsonProperty("MaxPeople")]
Эти то же

2024-04-04 07:27 UTC, dkobzin commented on MaksimKez/HW17/hw16/hw16/Models/MeetingSettings.cs
> +        [JsonProperty("MaxTime")]
И этот не нужен

2024-04-04 07:27 UTC, dkobzin commented on MaksimKez/HW17/hw16/hw16/Program.cs
> +            builder.Services.AddTransient<IGetRoomSettings, MeetingSettingsService>();
AddTransient смените на AddScoped. Имена интрефейса и сервиса должны совпадать в общем. Интерфейс должен иметь префикс I

2024-04-04 07:27 UTC, dkobzin commented on MaksimKez/HW17/hw16/hw16/Services/MeetingSettingsService.cs
> +            //var
Уберите пожалуйста закомментированный код.

2024-04-04 07:27 UTC, dkobzin commented on MaksimKez/HW17/hw16/hw16/Services/MeetingSettingsService.cs
> +            _configuration["MeetingRoomSettings:MaxPeople"] = meetingSettings.MaxPeople.ToString();
Тут что то будети подобное  configuration["Meetings"] = JsonSerializer.Serialize(meetings);

2024-04-04 07:29 UTC, dkobzin commented
Добрый день!

Посмотрите пожалуйста комментарии.

С уважением,

Дмитрий Кобзин
________________________________
From: MaksimKez ***@***.***>
Sent: Thursday, April 4, 2024 9:43 AM
To: dkobzin/tms-net15-onl ***@***.***>
Cc: Dmitry Kobzin ***@***.***>; Review requested ***@***.***>
Subject: [dkobzin/tms-net15-onl] Hw17 MaksimKez (PR #78)


Задание сделано, но есть недочет. После завершения работы новые (измененные) настройки не отображаются в appsettings.Development.json (как и в appsettings.json). Как это решить не знаю :(

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/dkobzin/tms-net15-onl/pull/78

Commit Summary

  *   c7defcd<https://github.com/dkobzin/tms-net15-onl/pull/78/commits/c7defcd2d6f81c2a7a0efcdf4e4a6319cf984d62> made partially
  *   cf0a511<https://github.com/dkobzin/tms-net15-onl/pull/78/commits/cf0a5113345b60fab7f353baead8032e2015d65a> made without saving

File Changes

(82 files<https://github.com/dkobzin/tms-net15-onl/pull/78/files>)

  *   M .gitignore<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947> (3)
  *   A MaksimKez/HW17/hw16/hw16.sln<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-6d65c0128c0ed3c62e42c77038a13bcf3621d655f452a6e3d833aba8458dd0bb> (25)
  *   A MaksimKez/HW17/hw16/hw16/Controllers/HomeController.cs<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-446b57dfe3a976ad05203a8c599a8bc9b0316f29a1729fc7e123500bdbbfe88a> (61)
  *   A MaksimKez/HW17/hw16/hw16/Models/ErrorViewModel.cs<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-2509a2a9672d1250de10e49d8174574c4008e1b97a23a7c66a6793664b38d1e2> (9)
  *   A MaksimKez/HW17/hw16/hw16/Models/MeetingSettings.cs<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-33ae5fa890c726a92bc2d163b3d911f432e7e08fd0c1aefbeaa4faf80561b0cf> (14)
  *   A MaksimKez/HW17/hw16/hw16/Program.cs<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-f12b177e11e7d33a6bc4d1c375a2871b378e07cb4e397f3514b4bb932ab08a65> (39)
  *   A MaksimKez/HW17/hw16/hw16/Properties/launchSettings.json<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-88a56613e318c861f362f738d59d12f78dcf8891e41672bccb4db17ced348d5f> (38)
  *   A MaksimKez/HW17/hw16/hw16/Services/IGetRoomSettings.cs<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-cd1fb7ec16a0c9d8228707263edc4d5bda982910fdbc529045503af3c7d51653> (10)
  *   A MaksimKez/HW17/hw16/hw16/Services/MeetingSettingsService.cs<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-d7842fe6f2c391ce0c9b945c2c414d97305b4b17570c63192c36e152cac492c0> (51)
  *   A MaksimKez/HW17/hw16/hw16/Views/Home/Index.cshtml<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-434f7807a21596a124e54f84e65a2e98909f0d9e078d3193e1a66e0ab32b26c1> (25)
  *   A MaksimKez/HW17/hw16/hw16/Views/Home/MyTest.cshtml<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-24e3e7b9d64606bddeca746e3d77584ace1f16c6aaf38a0aca1b0884b87eb18d> (12)
  *   A MaksimKez/HW17/hw16/hw16/Views/Home/Privacy.cshtml<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-996a2dac6980e9198869843cf9a8dc3984e47a5238a6d9545e0aff889b7b996b> (6)
  *   A MaksimKez/HW17/hw16/hw16/Views/Shared/Error.cshtml<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-ae16272fe85dde9f4bb632cc8c4ff1a9f0e857bb684ca0e0c4ebfdab1e4f8b4e> (25)
  *   A MaksimKez/HW17/hw16/hw16/Views/Shared/_Layout.cshtml<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-7a7497ea532074ed991647724264d639b51a3b2943cc1fe6b165c79c9e6823e2> (49)
  *   A MaksimKez/HW17/hw16/hw16/Views/Shared/_Layout.cshtml.css<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-49d4e4aa61a74e6456fb7dd92ca56a2fb8e60bf3181f5a3ff68a8ff08fb6f39a> (48)
  *   A MaksimKez/HW17/hw16/hw16/Views/Shared/_ValidationScriptsPartial.cshtml<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-85523d1f6c1cef9a9d96192fc474f29192dd4140c2a12b4f65dd0180498f02de> (2)
  *   A MaksimKez/HW17/hw16/hw16/Views/_ViewImports.cshtml<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-89cb3d0d4bbe68e64e39338f5db32464d44dbbd45726704ff444d1288c6383fe> (3)
  *   A MaksimKez/HW17/hw16/hw16/Views/_ViewStart.cshtml<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-94550e9f7ec7477a2e86db3adaccfdea739e44abfd6203333d0420f2bdcfda8a> (3)
  *   A MaksimKez/HW17/hw16/hw16/appsettings.Development.json<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-89c47034844a53a2db430d13e199bc4a34bee94f6ff1960dc314bd4ed88d5185> (14)
  *   A MaksimKez/HW17/hw16/hw16/appsettings.json<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-476efd71e0b3c859d9b1975c1e864c7657673a0b8ee82ed40da3701e5835ff02> (14)
  *   A MaksimKez/HW17/hw16/hw16/hw16.csproj<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-f97d0bc0a5d4b4f2a0398a3493058325d760dbd71d7ffb326fc977be294676ff> (13)
  *   A MaksimKez/HW17/hw16/hw16/hw16.csproj.user<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-8e56c93901dec28bb935bb5d383ee249490ded80cb76b86f4dc13236e9e9101f> (11)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/css/site.css<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-9e25520c521a58cbf985ba17093df6037f0f67a4a74015d89d713d41005fb7f9> (22)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/favicon.ico<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-7348f1cc48a2072dfb66ddcfe4509864ebbdf291c6733804e716c50199cba63f> (0)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/js/site.js<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-311ba521e17a66fb71405aa8b5bc11815796676ad8b9484dbd172e4b448d8ca2> (4)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/lib/bootstrap/LICENSE<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-b661bae74a089506b42cfd3e5f4d0508bb86454604af26627ad01b4a74582655> (22)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/lib/bootstrap/dist/css/bootstrap-grid.css<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-ebf1ffec5bd06006fd6c34b1abc8a831cf9d51981041c826a70bff4e9243cd1e> (4997)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/lib/bootstrap/dist/css/bootstrap-grid.css.map<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-4c50138ddd508a47444cd6273882f499667ce12df03653553ab17e82756f4a29> (1)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/lib/bootstrap/dist/css/bootstrap-grid.min.css<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-35702bd443ba5645e0c7c0f9e840918bb869dc30ff0f73665c8822d654247bff> (7)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/lib/bootstrap/dist/css/bootstrap-grid.min.css.map<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-03453e6e9ff15f16db131e5268955e3046c186de2581040dff34ff6d92e4cf91> (1)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/lib/bootstrap/dist/css/bootstrap-grid.rtl.css<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-8e76ea4f776bbb52b9c3f1cbfc4d43684319fa67c6e6bbc670bebcac0508925e> (4996)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/lib/bootstrap/dist/css/bootstrap-grid.rtl.css.map<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-6de590a9097a2cb6aed95e2892646ce9fa34153ce870218eec5694cf11dc8945> (1)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/lib/bootstrap/dist/css/bootstrap-grid.rtl.min.css<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-ba35d1946ef145a67ea5acf3542862be195caf6413c2c8c9734c9f214ae1f04d> (7)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/lib/bootstrap/dist/css/bootstrap-grid.rtl.min.css.map<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-f954796ea6105a5046f068eec3bf93736170d036379b0f7ade93302241e42c66> (1)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.css<https://github.com/dkobzin/tms-net15-onl/pull/78/files#diff-c789c7987a1d65f2a78d931ceb8ab0e07f906a75d2f206ddf1fea22ab3602efb> (427)
  *   A MaksimKez/HW17/hw16/hw16/wwwroot/lib/bootstrap/dist/css/bootstrap-reboot.css.map<https://github.com/dkobzin/tms-net15-onl/pu [...]

2024-04-05 20:38 UTC, MaksimKez commented on MaksimKez/HW17/hw16/hw16/Models/MeetingSettings.cs
> +    [Serializable]
Исправил

2024-04-05 20:38 UTC, MaksimKez commented on MaksimKez/HW17/hw16/hw16/Models/MeetingSettings.cs
> +        [JsonProperty("MaxPeople")]
Исправил

2024-04-05 20:38 UTC, MaksimKez commented on MaksimKez/HW17/hw16/hw16/Models/MeetingSettings.cs
> +        [JsonProperty("MaxTime")]
Исправил

2024-04-05 20:39 UTC, MaksimKez commented on MaksimKez/HW17/hw16/hw16/Program.cs
> +            builder.Services.AddTransient<IGetRoomSettings, MeetingSettingsService>();
Исправил

2024-04-05 20:39 UTC, MaksimKez commented on MaksimKez/HW17/hw16/hw16/Services/MeetingSettingsService.cs
> +            //var
Исправил

2024-04-05 21:48 UTC, MaksimKez commented on MaksimKez/HW17/hw16/hw16/Services/MeetingSettingsService.cs
> +            _configuration["MeetingRoomSettings:MaxPeople"] = meetingSettings.MaxPeople.ToString();
переделал. я все еще не понимаю в чем проблема в коде. На время "сессии" оно все отображается, но не записывается. Очень много раз прошел по коду и все еще не смог решить

2024-04-06 10:15 UTC, dkobzin commented on MaksimKez/HW17/hw16/hw16/Services/MeetingSettingsService.cs
> +            _configuration["MeetingRoomSettings:MaxPeople"] = meetingSettings.MaxPeople.ToString();
Посмотрите в отладке как это происходит

2024-04-06 10:17 UTC, dkobzin commented
Я думаю что вам надо поотлаживать код.

С уважением,

Дмитрий Кобзин
________________________________
From: MaksimKez ***@***.***>
Sent: Saturday, April 6, 2024 12:48 AM
To: dkobzin/tms-net15-onl ***@***.***>
Cc: Dmitry Kobzin ***@***.***>; Review requested ***@***.***>
Subject: Re: [dkobzin/tms-net15-onl] Hw17 MaksimKez (PR #78)


@MaksimKez commented on this pull request.

________________________________

In MaksimKez/HW17/hw16/hw16/Services/MeetingSettingsService.cs<https://github.com/dkobzin/tms-net15-onl/pull/78#discussion_r1554339976>:

> +        private readonly IConfiguration _configuration;
+
+        public MeetingSettingsService(IConfiguration configuration)
+        {
+           _configuration = configuration;
+        }
+
+        void IGetRoomSettings.SaveSettings(MeetingSettings meetingSettings)
+        {
+            // изменить в appsettings.Development.json по ключу значения MeetingSettings
+            //var jsonStr = File.ReadAllText("appsettings.Development.json");
+            //var jsonSettingsToChange = System.Text.Json.JsonSerializer.Deserialize<MeetingSettings>(jsonStr);
+            //jsonSettingsToChange.MaxPeople = meetingSettings.MaxPeople;
+            //jsonSettingsToChange.MaxTime = meetingSettings.MaxTime;
+            //var
+            _configuration["MeetingRoomSettings:MaxPeople"] = meetingSettings.MaxPeople.ToString();


переделал. я все еще не понимаю в чем проблема в коде. На время "сессии" оно все отображается, но не записывается. Очень много раз прошел по коду и все еще не смог решить

—
Reply to this email directly, view it on GitHub<https://github.com/dkobzin/tms-net15-onl/pull/78#discussion_r1554339976>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARXU4OPRDYNSH4EPQIKE3U3Y34L3LAVCNFSM6AAAAABFWUVMRWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSOBUGI2DINZYGQ>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-04-08 14:27 UTC, MaksimKez commented on MaksimKez/HW17/hw16/hw16/Services/MeetingSettingsService.cs
> +            _configuration["MeetingRoomSettings:MaxPeople"] = meetingSettings.MaxPeople.ToString();
Исправлено, сама идея как исправить просто ужасна, но оно все работает и работает стабильно.

2024-04-09 05:38 UTC, merged