Toffee galka home work 18
dkobzin/tms-net15-onl pull request #80
Opened 2024-04-05 12:25 UTC by ToffeeGalka

Toffee galka home work 18

2024-04-06 10:09 UTC, dkobzin requested changes

2024-04-06 10:09 UTC, dkobzin commented on ToffeeGalka/HomeWork18/Controllers/MeetingRoomController.cs
> +            return View("MeetingRoom");
Тут можно добавить передачу модели,, минуя  ViewBag

2024-04-06 10:11 UTC, dkobzin requested changes

2024-04-06 10:11 UTC, dkobzin commented on ToffeeGalka/HomeWork18/Controllers/MeetingRoomController.cs
> +        public IActionResult EditRoom()
Тут можно передать измененную модель через  форму

2024-04-06 10:11 UTC, dkobzin commented on ToffeeGalka/HomeWork18/Views/MeetingRoom/Index.cshtml
> +﻿@{
Тут можно принять модель и дальше передать в отобразить в форме

2024-04-08 12:21 UTC, ToffeeGalka commented on ToffeeGalka/HomeWork18/Views/MeetingRoom/Index.cshtml
> +﻿@{
я использую Views/MeetingRoom/MeetingRoom.cshtml

2024-04-08 12:21 UTC, ToffeeGalka commented on ToffeeGalka/HomeWork18/Controllers/MeetingRoomController.cs
> +            return View("MeetingRoom");
fix

2024-04-08 12:47 UTC, merged