Homework 16 - 18
dkobzin/tms-net15-onl pull request #81
Opened 2024-04-06 11:08 UTC by BelkL1ne

Homework 16 - 18

2024-04-06 11:50 UTC, dkobzin requested changes

2024-04-06 11:50 UTC, dkobzin commented on BelkL1ne/Homework 16-18/Homework 16/DAL/ApplicationDbContext.cs
> +    }
Это все можно заменить на работу с appSettings.json -  Configuration и IConfiguration. Просто тут надо реализовывать запись и получение данных из файла настроек приложения

2024-04-06 11:50 UTC, dkobzin commented on BelkL1ne/Homework 16-18/Homework 16/Views/Home/MeetingRoom.cshtml
> +*@
Добавьте тип модели

2024-04-06 11:50 UTC, dkobzin commented on BelkL1ne/Homework 16-18/Homework 16/Controllers/HomeController.cs
> +            return View(meetingRoomViewModel);
Зачем передаем модель в представление индекс? Только чтобы посмотреть  ее? Представление MeetingRoom - не используется

2024-04-06 11:50 UTC, dkobzin commented on BelkL1ne/Homework 16-18/Homework 16/Views/Home/MeetingRoom.cshtml
> +<form method="post" asp>
Добавьте атрибуты для контроллера и экшена

2024-04-06 11:50 UTC, dkobzin commented on BelkL1ne/Homework 16-18/Homework 16/Views/Shared/_Layout.cshtml
> +                    </ul>
Добавьте верстку для страницы MeetingRoom по аналогии с страницей Home

2024-04-06 16:51 UTC, BelkL1ne commented on BelkL1ne/Homework 16-18/Homework 16/Controllers/HomeController.cs
> +            return View(meetingRoomViewModel);
Ну вообще да, только чтобы посмотреть на нее

2024-04-06 16:54 UTC, BelkL1ne commented on BelkL1ne/Homework 16-18/Homework 16/Views/Home/MeetingRoom.cshtml
> +*@
Добавил

2024-04-06 17:36 UTC, BelkL1ne commented on BelkL1ne/Homework 16-18/Homework 16/Views/Shared/_Layout.cshtml
> +                    </ul>
Добавил

2024-04-06 17:52 UTC, BelkL1ne commented on BelkL1ne/Homework 16-18/Homework 16/Views/Home/MeetingRoom.cshtml
> +<form method="post" asp>
Добавил

2024-04-07 07:47 UTC, dkobzin commented on BelkL1ne/Homework 16-18/Homework 16/DAL/ApplicationDbContext.cs
> +    }
Можно  и в сервисе оставить.

2024-04-07 07:48 UTC, dkobzin commented on BelkL1ne/Homework 16-18/Homework 16/Views/Home/MeetingRoom.cshtml
> +*@
Не видно изменений

2024-04-07 07:48 UTC, dkobzin commented on BelkL1ne/Homework 16-18/Homework 16/Views/Home/MeetingRoom.cshtml
> +<form method="post" asp>
Не видно изменений

2024-04-07 07:49 UTC, dkobzin requested changes

2024-04-07 07:49 UTC, dkobzin commented on BelkL1ne/Homework 16-18/Homework 16/Views/Shared/_Layout.cshtml
> +                    </ul>
Не видно изменений

2024-04-10 16:07 UTC, dkobzin requested changes

2024-04-11 05:45 UTC, dkobzin approved these changes

2024-04-11 05:46 UTC, merged