Стас Колесник - 19HW
dkobzin/tms-net15-onl pull request #86
Opened 2024-04-09 18:34 UTC by mywwave

Добавить в проект предыдущего занятия Middleware для обработки исключений.
Добавить фильтр, который устанавливает время запроса в Header ответа

2024-04-10 09:57 UTC, dkobzin requested changes

2024-04-10 10:31 UTC, mywwave commented on StasKolesnik/HomeWork19/Program.cs
> +var app = builder.Build();
Так middleware же и так подключен через app.UseMiddleware

2024-04-12 06:19 UTC, dkobzin commented on StasKolesnik/HomeWork19/Program.cs
> +var app = builder.Build();
Так там надо отдельно добавлять его. При использовании будет выкидывать exception

2024-04-12 06:24 UTC, dkobzin approved these changes

2024-04-12 06:24 UTC, merged